<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="63820" started-at="2016-09-29T08:35:33Z" finished-at="2016-09-29T08:36:37Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="63820" started-at="2016-09-29T08:35:33Z" finished-at="2016-09-29T08:36:37Z">
      <class name="testScript.Scenrio_Login">
        <test-method status="PASS" signature="intitalSetup()[pri:0, instance:testScript.Scenrio_Login@13afe78]" name="intitalSetup" is-config="true" duration-ms="281" started-at="2016-09-29T14:05:33Z" finished-at="2016-09-29T14:05:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intitalSetup -->
        <test-method status="PASS" signature="launch_App()[pri:0, instance:testScript.Scenrio_Login@13afe78]" name="launch_App" is-config="true" duration-ms="12885" started-at="2016-09-29T14:05:34Z" finished-at="2016-09-29T14:05:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch_App -->
        <test-method status="PASS" signature="Invalid_login(java.util.Map)[pri:0, instance:testScript.Scenrio_Login@13afe78]" name="Invalid_login" duration-ms="3764" started-at="2016-09-29T14:05:47Z" data-provider="InvalidLogin" finished-at="2016-09-29T14:05:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Expected=Sorry we were unable to complete this step because :, UserName=kseyr, Execute=Y, Script_id=Invalid_login, Pwd=syrf, TCID=TC_01, order=1.0}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Invalid_login -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:testScript.Scenrio_Login@13afe78]" name="teardown" is-config="true" duration-ms="368" started-at="2016-09-29T14:05:50Z" finished-at="2016-09-29T14:05:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="launch_App()[pri:0, instance:testScript.Scenrio_Login@13afe78]" name="launch_App" is-config="true" duration-ms="8545" started-at="2016-09-29T14:05:51Z" finished-at="2016-09-29T14:05:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch_App -->
        <test-method status="PASS" signature="Invalid_login(java.util.Map)[pri:0, instance:testScript.Scenrio_Login@13afe78]" name="Invalid_login" duration-ms="27359" started-at="2016-09-29T14:05:59Z" data-provider="InvalidLogin" finished-at="2016-09-29T14:06:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Expected=Sorry we were unable to complete this step because :, UserName=, Execute=Y, Script_id=Invalid_login, Pwd=, TCID=TC_06, order=1.0}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Invalid_login -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:testScript.Scenrio_Login@13afe78]" name="teardown" is-config="true" duration-ms="47" started-at="2016-09-29T14:06:27Z" finished-at="2016-09-29T14:06:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
        <test-method status="PASS" signature="launch_App()[pri:0, instance:testScript.Scenrio_Login@13afe78]" name="launch_App" is-config="true" duration-ms="7774" started-at="2016-09-29T14:06:27Z" finished-at="2016-09-29T14:06:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launch_App -->
        <test-method status="FAIL" signature="Valid_login(java.util.Map)[pri:0, instance:testScript.Scenrio_Login@13afe78]" name="Valid_login" duration-ms="2448" started-at="2016-09-29T14:06:35Z" data-provider="ValidLogin" finished-at="2016-09-29T14:06:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Expected=qtpworld2008, UserName=qtpworld2008@gmail.com, Execute=Y, Script_id=Valid_login, Pwd=learn123, TCID=TC_07, order=1.0}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	page not loaded expected [rediff] but found [rediff.com ! Books Online],
	failed as the expected was qtpworld2008  and actual is qtpworld2008 g expected [qtpworld2008] but found [qtpworld2008 g]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	page not loaded expected [rediff] but found [rediff.com ! Books Online],
	failed as the expected was qtpworld2008  and actual is qtpworld2008 g expected [qtpworld2008] but found [qtpworld2008 g]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at testScript.Scenrio_Login.Valid_login(Scenrio_Login.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Valid_login -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:testScript.Scenrio_Login@13afe78]" name="teardown" is-config="true" duration-ms="31" started-at="2016-09-29T14:06:37Z" finished-at="2016-09-29T14:06:37Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- testScript.Scenrio_Login -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
